name: CI

on:
  push:
    branches:
      - codewars
  pull_request:

jobs:
  check:
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md
    # CMake 3.23.2
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Build
        run: |
          mkdir -p ./build
          cd ./build
          cmake ..
          make
